### ISSUE TITLE
No module named 'osgeo' on Debian 10 

### ISSUE THREAD

**Issue by naim5am** [plant99/felicette#13]
```
(env) elmos@furni:~/GIS_dumps$ felicette -c "51.311454,4.867640" 
Traceback (most recent call last):
  File "/home/elmos/.local/bin/felicette", line 5, in <module>
    from felicette.cli import main
  File "/home/elmos/.local/lib/python3.6/site-packages/felicette/cli.py", line 13, in <module>
    from felicette.sat_processor import process_landsat_data
  File "/home/elmos/.local/lib/python3.6/site-packages/felicette/sat_processor.py", line 9, in <module>
    from felicette.utils.gdal_pansharpen import gdal_pansharpen
  File "/home/elmos/.local/lib/python3.6/site-packages/felicette/utils/gdal_pansharpen.py", line 35, in <module>
    from osgeo import gdal
ModuleNotFoundError: No module named 'osgeo'
```

I followed installation instructions and made sure I'm using python3. Also  tried pip3 install -r requirements.txt. Also, tried updating pip in the virtual environment via https://bootstrap.pypa.io/get-pip.py .. same same
Any other suggestions? thanks

**Comment by plant99** [comment]
If you've installed 'gdal' properly as explained [here](https://github.com/plant99/felicette#debian).

You have to do 
```
$ gdal-config --version
<version-number>

$ pip install numpy GDAL=={version-number}
```
This installs 'osgeo' package, I think felicette would work then.

**Comment by plant99** [comment]
Also, if `xdg-open` doesn't work, please look into #1

**Comment by naim5am** [comment]
> Also, if `xdg-open` doesn't work, please look into #1

```
xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.

```
xdg-iopen works

**Comment by plant99** [comment]
Does https://github.com/plant99/felicette/issues/13#issuecomment-663999536 work? If yes, please close the issue?

**Comment by naim5am** [comment]
> If you've installed 'gdal' properly as explained [here](https://github.com/plant99/felicette#debian),
> 
> You have to do
> 
> ```
> $ gdal-config --version
> <version-number>
> 
> $ pip install numpy GDAL=={version-number}
> ```
> 
> This installs 'osgeo' package, I think felicette would work then.

already done. That's what I did first time. Weird. I wiped stuff and installed again, couldn't reproduce the error. closing
