### ISSUE TITLE
Unknown place = The Netherlands

### ISSUE THREAD

**Issue by huphtur** [plant99/felicette#3]
The [image](https://camo.githubusercontent.com/d06460e9459584d65aca680e9ad2a10d298af3e7/68747470733a2f2f692e696d6775722e636f6d2f6f6569726332512e6a7067) titled "Unknown place" in the [Sample images generated by felicette](https://github.com/plant99/felicette/wiki/Sample-images-generated-by-felicette) wiki is of [the northern part of The Netherlands](https://goo.gl/maps/EGCZm6XezUKGP42g6).

**Comment by plant99** [comment]
Wow, I just checked. Thanks, fixing this.
