### ISSUE TITLE
Flag -p generates error

### ISSUE THREAD

**Issue by arjantenhoopen** [plant99/felicette#37]
Using the -p flag to get even more eye-cany generates an error. I reveived this error during usage of the docker image. However I assume this is an error in the code..
Here is the output, first without the -p flag then with:

arjan@arjanpc:/tmp/lm> docker run -it -v "$PWD"/felicette-data:/root/felicette-data milhouse1337/felicette felicette --no-preview  -v -l Neede
✗ required data doesn't exist, downloading green band
b3: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60.0M/60.0M [00:04<00:00, 13.8MB/s]
✗ required data doesn't exist, downloading red band
b4: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62.0M/62.0M [00:04<00:00, 14.1MB/s]
✗ required data doesn't exist, downloading NIR band
b5: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68.0M/68.0M [00:05<00:00, 13.8MB/s]
Let's make our 🌍 imagery a bit more colorful for a human eye!
Generated 🌍 images!🎉
Please wait while I resize and crop the image :) 
GeoTIFF saved at:
/root/felicette-data/LC08_L1TP_197024_20210305_20210312_01_T1/LC08_L1TP_197024_20210305_20210312_01_T1-vegetation.tiff
JPEG image saved at:
/root/felicette-data/LC08_L1TP_197024_20210305_20210312_01_T1/LC08_L1TP_197024_20210305_20210312_01_T1-vegetation.jpeg
sh: 1: xdg-open: not found

arjan@arjanpc:/tmp/lm> docker run -it -v "$PWD"/felicette-data:/root/felicette-data milhouse1337/felicette felicette --no-preview  -p -v -l Neede
Traceback (most recent call last):
  File "/usr/local/bin/felicette", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/felicette/cli.py", line 73, in main
    item = search_satellite_data(coordinates, 10, product=product)
  File "/usr/local/lib/python3.7/dist-packages/felicette/sat_downloader.py", line 53, in search_satellite_data
    search_items = search.items()
  File "/usr/local/lib/python3.7/dist-packages/satsearch/search.py", line 90, in items
    found = self.found(headers=headers)
  File "/usr/local/lib/python3.7/dist-packages/satsearch/search.py", line 62, in found
    results = self.query(url=url, headers=headers, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/satsearch/search.py", line 80, in query
    raise SatSearchError(response.text)
satsearch.search.SatSearchError: index_not_found_exception
arjan@arjanpc:/tmp/lm> 

Cheers,
Arjan

**Comment by plant99** [comment]
Could you use `-pan` option and try again? It's only possible with Landsat product. The full command would be
```
 felicette --no-preview -pan -v -l Neede
```

**Comment by arjantenhoopen** [comment]
Yes -pan works! I just wanted to point out that the -p doesn't work. I think you changed the old -p into the new -pan.

**Comment by plant99** [comment]
Yep, after the tool supported Sentinel, that release changed the flag to do panchromatic enhancements.
