### ISSUE TITLE
Fails to re-download data if there was a network error 

### ISSUE THREAD

**Issue by mantlecurve** [plant99/felicette#4]
If any of the bands (blue, green or red) fails during the download, felicette doesn't re-download it. Rerunning the program again for the specific place shows the required data exists for the said band. But in reality it is an incomplete download. This throws an error

`rasterio.errors.RasterioIOError: Read or write failed. /home/mithun/felicette-data/LC81430542020100/LC81430542020100-b4.tiff, band 1: IReadBlock failed at X offset 1, Y offset 6: TIFFReadEncodedTile() failed.`

Current workaround is to delete the folder and run again.

**Comment by plant99** [comment]
I'd prioritize this and add it to To-Do. 

Let's see if there are options to validate check-sums of band files, so it doesn't download the required data all over again.
Another way is to handle the removal of the data directory on `except rasterio.errors.RasterioIOError` in `felicette/sat_processor.py`

**Comment by mantlecurve** [comment]
If checksum can be implemented, that would be the best option 

Or can go with '--refresh' flag 🚩

The folder delete on exception should be done on network error and not after the above mentioned exception. If the first band is error, the second and third gets downloaded before the exception, which would be useless.

**Comment by plant99** [comment]
https://github.com/plant99/felicette/commit/3447b785aec583b1055481fe076fdaa6f52290a9 this commit partially fixes this issue, by catching the `RasterIOError`, deleting the data dirs, and reattempting download and processing.

**Comment by plant99** [comment]
A long term solution to this would be using check-sums, but will add this to to-do, due to less bandwidth. Feel free to reopen the issue if the problem persists after the next release
