### ISSUE TITLE
Feature request: fail early if there is no satellite imagery for requested area

### ISSUE THREAD

**Issue by strogonoff** [plant99/felicette#7]
For some locations, images for all bands are entirely black (they still weigh more than 30 MB each though). I assume this is because of unavailable satellite imagery. This could be detected before resources are spent on color-correcting and sharpening🤔

**Comment by plant99** [comment]
Could you please name a location for which this happens? The 'preview image' is of size in KBs, so we can verify it's contrast/threshold of rgb values to make a decision? That is, before downloading any band data.

**Comment by strogonoff** [comment]
@plant99: Black images obtained for `-c 114.164317 22.325492 -p`; all band downloaded successfully. This happened for one out of three locations I tried; two in Asia and one in Northern America.

**Comment by strogonoff** [comment]
![LC82241992019216-preview](https://user-images.githubusercontent.com/292959/88464402-68df5e80-cef5-11ea-849e-3f136d90767e.jpg)

Yes, I should’ve tried the preview first. It looks like this, by the way😱

**Comment by plant99** [comment]
Oh wow, this is some seriously bad data. Thanks for raising the issue again, will look into this.

**Comment by 5h15h** [comment]
yes ... i am getting the same issue for Seattle with:  "felicette -pre -p -l "Seattle"

**Comment by plant99** [comment]
https://github.com/plant99/felicette/commit/02e44f8f38443eb4811919b8607d2ed460374354

^ commit partially fixes it by making preview option set by default.
